/*
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CloseTransactionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T22:49:47.436+03:00")
public class CloseTransactionResponse {
  @SerializedName("transaction_id")
  private String transactionId = null;

  @SerializedName("synthesize_text_size")
  private Long synthesizeTextSize = null;

  public CloseTransactionResponse transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(value = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public CloseTransactionResponse synthesizeTextSize(Long synthesizeTextSize) {
    this.synthesizeTextSize = synthesizeTextSize;
    return this;
  }

   /**
   * Get synthesizeTextSize
   * @return synthesizeTextSize
  **/
  @ApiModelProperty(value = "")
  public Long getSynthesizeTextSize() {
    return synthesizeTextSize;
  }

  public void setSynthesizeTextSize(Long synthesizeTextSize) {
    this.synthesizeTextSize = synthesizeTextSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloseTransactionResponse closeTransactionResponse = (CloseTransactionResponse) o;
    return Objects.equals(this.transactionId, closeTransactionResponse.transactionId) &&
        Objects.equals(this.synthesizeTextSize, closeTransactionResponse.synthesizeTextSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, synthesizeTextSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloseTransactionResponse {\n");

    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    synthesizeTextSize: ").append(toIndentedString(synthesizeTextSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

