/*
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ExceptionModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T22:49:47.436+03:00")
public class ExceptionModel {
  @SerializedName("reason")
  private String reason = null;

  @SerializedName("message")
  private String message = null;

  public ExceptionModel reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason of exception
   * @return reason
  **/
  @ApiModelProperty(required = true, value = "Reason of exception")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ExceptionModel message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message of exception
   * @return message
  **/
  @ApiModelProperty(required = true, value = "Message of exception")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionModel exceptionModel = (ExceptionModel) o;
    return Objects.equals(this.reason, exceptionModel.reason) &&
        Objects.equals(this.message, exceptionModel.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionModel {\n");

    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

