/*
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StartSessionRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T22:49:47.436+03:00")
public class StartSessionRequest {
  @SerializedName("username")
  private String username = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("domain_id")
  private Long domainId = null;

  public StartSessionRequest(String username, String password, Long domainId) {
    this.username = username;
    this.password = password;
    this.domainId = domainId;
  }

  public StartSessionRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * User login
   * @return username
  **/
  @ApiModelProperty(example = "api_administrator", required = true, value = "User login")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public StartSessionRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * User password
   * @return password
  **/
  @ApiModelProperty(example = "123", required = true, value = "User password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public StartSessionRequest domainId(Long domainId) {
    this.domainId = domainId;
    return this;
  }

   /**
   * User domain identifier
   * @return domainId
  **/
  @ApiModelProperty(example = "203", required = true, value = "User domain identifier")
  public Long getDomainId() {
    return domainId;
  }

  public void setDomainId(Long domainId) {
    this.domainId = domainId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StartSessionRequest startSessionRequest = (StartSessionRequest) o;
    return Objects.equals(this.username, startSessionRequest.username) &&
        Objects.equals(this.password, startSessionRequest.password) &&
        Objects.equals(this.domainId, startSessionRequest.domainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, password, domainId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StartSessionRequest {\n");

    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    domainId: ").append(toIndentedString(domainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

