/*
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * SynthesizeVoiceType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T22:49:47.436+03:00")
public class SynthesizeVoiceType {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Gender of voice
   */
  @JsonAdapter(GenderEnum.Adapter.class)
  public enum GenderEnum {
    UNDEFINED("UNDEFINED"),
    
    MALE("MALE"),
    
    FEMALE("FEMALE");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GenderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GenderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GenderEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return GenderEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("gender")
  private GenderEnum gender = null;

  public SynthesizeVoiceType id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Voice id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Voice id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SynthesizeVoiceType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of voice
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of voice")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SynthesizeVoiceType gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender of voice
   * @return gender
  **/
  @ApiModelProperty(required = true, value = "Gender of voice")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SynthesizeVoiceType synthesizeVoiceType = (SynthesizeVoiceType) o;
    return Objects.equals(this.id, synthesizeVoiceType.id) &&
        Objects.equals(this.name, synthesizeVoiceType.name) &&
        Objects.equals(this.gender, synthesizeVoiceType.gender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, gender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SynthesizeVoiceType {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

