/*
 * TTS documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * WebSocketSynthesizeRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T22:49:47.436+03:00")
public class WebSocketSynthesizeRequest {
  @SerializedName("text")
  private WebSocketTextParam text = null;

  @SerializedName("voice_name")
  private String voiceName = null;

  @SerializedName("audio")
  private String audio = null;

  public WebSocketSynthesizeRequest(WebSocketTextParam text, String voiceName, String audio) {
    this.text = text;
    this.voiceName = voiceName;
    this.audio = audio;
  }

  public WebSocketSynthesizeRequest text(WebSocketTextParam text) {
    this.text = text;
    return this;
  }

   /**
   * Text for synthesize to speech
   * @return text
  **/
  @ApiModelProperty(required = true, value = "Text for synthesize to speech")
  public WebSocketTextParam getText() {
    return text;
  }

  public void setText(WebSocketTextParam text) {
    this.text = text;
  }

  public WebSocketSynthesizeRequest voiceName(String voiceName) {
    this.voiceName = voiceName;
    return this;
  }

   /**
   * Name of name
   * @return voiceName
  **/
  @ApiModelProperty(required = true, value = "Name of name")
  public String getVoiceName() {
    return voiceName;
  }

  public void setVoiceName(String voiceName) {
    this.voiceName = voiceName;
  }

  public WebSocketSynthesizeRequest audio(String audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Format of response audio
   * @return audio
  **/
  @ApiModelProperty(example = "audio/s16le", required = true, value = "Format of response audio")
  public String getAudio() {
    return audio;
  }

  public void setAudio(String audio) {
    this.audio = audio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebSocketSynthesizeRequest webSocketSynthesizeRequest = (WebSocketSynthesizeRequest) o;
    return Objects.equals(this.text, webSocketSynthesizeRequest.text) &&
        Objects.equals(this.voiceName, webSocketSynthesizeRequest.voiceName) &&
        Objects.equals(this.audio, webSocketSynthesizeRequest.audio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, voiceName, audio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebSocketSynthesizeRequest {\n");

    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    voiceName: ").append(toIndentedString(voiceName)).append("\n");
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

