spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    username: postgres
    password: postgres
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/ml_db?currentSchema=handled_data

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:liquibase/db-changelog.xml

server:
  port: 9090

vaadin:
  urlMapping: /app/*
